package com.dogukanincee.jetpackcomposetodoapp.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * This class represents a single task in the to-do list.
 *
 * @property id The unique identifier for this task. It is autogenerated by Room.
 * @property title The title of the task.
 * @property description The description of the task.
 * @property completed Whether or not the task has been completed.
 */
@Entity(tableName = "tasks")
data class Task(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    val completed: Boolean = false
)
